apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: weather-raw
  namespace: data
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
