apiVersion: v1
kind: Pod
metadata:
  name: checkpoint-debug
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: checkpoint
          mountPath: /checkpoint
  volumes:
    - name: checkpoint
      persistentVolumeClaim:
        claimName: spark-checkpoint-pvc
