apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: weather-s3-to-silver
  namespace: default
spec:
  type: Python
  mode: cluster
  sparkVersion: 3.3.3

  image: spark-weather-silver:3.3.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/silver_from_s3.py

  restartPolicy:
    type: Never

  sparkConf:
    spark.hadoop.fs.s3a.endpoint: s3.amazonaws.com
    spark.hadoop.fs.s3a.aws.credentials.provider: com.amazonaws.auth.DefaultAWSCredentialsProviderChain
    spark.sql.parquet.enableVectorizedReader: "false"
    spark.sql.parquet.outputTimestampType: "TIMESTAMP_MICROS"
    spark.sql.parquet.int96RebaseModeInRead: "CORRECTED"
    spark.sql.parquet.datetimeRebaseModeInRead: "CORRECTED"

  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: S3_INPUT
        value: s3a://hust-bucket-storage/weather_silver/
      - name: SILVER_PATH
        value: /data/silver/weather

      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY

    volumeMounts:
      - name: silver
        mountPath: /data/silver

  executor:
    instances: 2
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: silver
        mountPath: /data/silver

  volumes:
    - name: silver
      persistentVolumeClaim:
        claimName: spark-silver-pvc
